{''
 'name': 'Apartment Record',
 'summary': """This module will add a record to store apartment details""",
 'version': '10.0.1.0.0',
'sequence':'-40',
 'description': """This module will add a record to store apartment details""",
 'author': 'Anzal',
 'company': 'Cybrosys Techno Solutions',
 'website': 'https://www.cybrosys.com',
 'category': 'Tools',
 'depends': ['mail',],
 'license': 'AGPL-3',
 'data': ['security/ir.model.access.csv',
 'data/data.xml',
 'views/customer.xml',
 'views/enquiry.xml',
 'views/project.xml',
 'views/blocks.xml',
 'views/floors.xml',
 'views/units.xml',
 'views/flats.xml',
 'views/sales.xml',
 'views/salesteam.xml',
'reports/report.xml',
'reports/apartment_invoice.xml',

          ],
 'demo': [],
 'installable': True,
 'auto_install': False,
 'application' : True
 }
