{''
 'name': 'Hospital Record',
 'summary': """This module will add a record to store student details""",
 'version': '10.0.1.0.0',
 'sequence': '-10',
 'description': """This module will add a record to store student details""",
 'author': 'Anzal',
 'company': 'Cybrosys Techno Solutions',
 'website': 'https://www.cybrosys.com',
 'category': 'Tools',
 'depends': ['mail', 'sale',
             ],
 'license': 'AGPL-3',
 'data': ['security/ir.model.access.csv',
          'data/data.xml',
          'wizard/create_appoinment.xml',
          'views/patient.xml',
          'views/kids.xml',
          'views/appoinment.xml',
          'views/doctor.xml',
          'reports/report.xml',
          'reports/appointment_receipt.xml',
          'reports/patient_id.xml',
          'reports/appoinment_invoice.xml',
          'reports/inherit_sale_order.xml',

          ],
 'demo': [],
 'installable': True,
 'auto_install': False,
 'application': True
 }
